### ISSUE TITLE
Payment amount on Oxipay page sometimes does not include Shipping Cost

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#10]
There are occasions where the Shipping Cost is not included in the Payment Price on the first Oxipay page, instead it only uses the Product Cost.
Tax costs also need to be considered.

**Comment by blueninja2** [comment]
Hi,

I have re-tested and the issue is still occuring.

The order on the Magento store was for $255 ($250 for the iPhone and $5 for the Shipping Fee) as per **Image 1**:

However, on Oxipay it shows that the order total is $250 and not $255 - see Image 2.

Also the email receipt from Oxipay shows that the order total is $250 and not $255 - see Image 3.

The expectation is that the order total on Oxipay and the email receipt should be $255 so it seems that the shipping costs are still not being included in the Payment Price.

**Image 1**
![image](https://cloud.githubusercontent.com/assets/22509613/23148788/9c48238a-f837-11e6-8f94-36fcadcfb43c.png)

**Image 2**
![image](https://cloud.githubusercontent.com/assets/22509613/23148825/c8c2cfc8-f837-11e6-93fc-2485e220fcc5.png)

**Image 3**
![image](https://cloud.githubusercontent.com/assets/22509613/23148801/a9f011be-f837-11e6-9d61-662485572724.png)

**Comment by blueninja2** [comment]
Have tested the fix and it passed.

1 - Confirmed that totals now include the shipping cost.
2 - Have also configured a Tax Rate for the store, and can confirm that Oxipay was including the additional tax in its calculation.
