### ISSUE TITLE
[QAIT]: Proper error message is not appearing on trying to Place order using Oxipay when inventory is out of stock.  

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-2.x#39]
Steps:
1) Add product to cart
2) Navigate to check out page
3) Enter Shipping and billing details
4) Navigate to Review & payments window
5) Select oxipay 
6) Navigate to Admin panel and decrease inventory to zero for same Item
7) Flush Magento cache
8) Now try to Place order 

Result:
Warning message appear as "An error occurred on the server. Please try to Place the order again."

Expected:
Warning message should appear as "Some of the products are currently out of stock"

Screen Cast: http://screencast-o-matic.com/watch/cbhQ6VXOxW

Test Case: #84 - When user selects Oxipay payment method after inventory changes to zero from admin, it should display message as 'Some of the products are currently out of stock'.

Tech Stack
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
Magento ver. 2.1.6
oxipay-magento-2.x_v0.0.14

**Comment by esteban-terem** [comment]
Hi. The plugin currently doesn't support a custom message for this case. Also, it is possible that is not feasible to implement this functionality at a Payment Gateway level because none of the Payment Gateway code is involved in this case ([reference](https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L76)).

As an example/reference, the internal Magento *Check/Money* Order payment method also behaves in the same way:
![image](https://cloud.githubusercontent.com/assets/26374597/25878245/a4d09862-356c-11e7-8dfa-315ff43ea5cd.png)

Extra info:
This is the only message we receive from the Magento engine in this case: *"message":"An error occurred on the server. Please try to place the order again."*

```
\/var\/www\/html\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(125, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n# 1 
\/var\/www\/html\/var\/generation\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(26): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)\n# 2 
[internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(125, Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))\n# 3
\/var\/www\/html\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n# 4 
\/var\/www\/html\/app\/code\/Magento\/Webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n# 5 
\/var\/www\/html\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n# 6 
\/var\/www\/html\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n# 7 
\/var\/www\/html\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n# 8 
\/var\/www\/html\/index.php(41): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n# 9 
{main}"}
```

**Comment by blueninja2** [comment]
Agree with you Esteban, because this is an issue with Magento and there is no obvious fix as well as the likelihood of this occurring is relatively low and also because its the same behaviour that the check/money order exhibits, we will close this issue.
