### ISSUE TITLE
Shipping/Billing Country other than AU and NZ being accepted

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#8]
![image](https://cloud.githubusercontent.com/assets/24661377/22233356/bf272940-e23f-11e6-9acc-b232b20a5e69.png)

![image](https://cloud.githubusercontent.com/assets/24661377/22233270/1fe8ad18-e23f-11e6-854a-36ca9ca170fc.png)

The service is accepting Countries outside AU and NZ.
Oxipay should only be a payment option in these countries, and return a message similar to the attached.

**Comment by blueninja2** [comment]
Hi,

Issue is still occuring, here I was able to type in an address in France however I was able to proceed with payment to the Oxipay Gateway and was not blocked at the shopping cart level.

Can you please change it so that only addresses in Australia or New Zealand are allowed for Oxipay?

![image](https://cloud.githubusercontent.com/assets/22509613/23147300/bff995b6-f82d-11e6-8ef5-7e0c1fdc58b4.png)

**Comment by blueninja2** [comment]
**There's a few issues with the current fix:**

**1 -** If a user selects a country other than AU/NZ then Oxipay will not be displayed as a payment option.

**2 -** The only way to trigger the error message is put in AU/NZ in checkout screen, select Oxipay and then edit address and put in a country other than AU/NZ.

**3 -** A user can put in the USA as their country will will display other payment options such as cash/cheque (Oxipay will not be displayed since the country is not AU/NZ). However, the user can edit the country to AU and Oxipay will still not be displayed as a payment option.

**4 -** The error message is not static - i.e. it disappears after about 5 seconds or when the user interacts with the page. We would like this changes so that it becomes permanent until the user provides correct values.

**We would like to change this so that:**

**1 -** Oxipay is always visible as a payment option regardless of the country that the user types in.

**2 -** If the country is AU/NZ then no error message is displayed and user can progress to the Oxipay site.

**3 -** If the country is not AU/NZ then the error message is displayed.

**Comment by iugo-josh** [comment]
I've pushed a new commit to PR #23 to address the feedback regarding the removal of the payment option when the user selects an address outside of Australia or New Zealand.

To property test this change, you will need to delete the row from the 'core_config_data' table with the path 'payment/oxipay_gateway/allowspecific'. You will also need to clear the cache.

**Comment by blueninja2** [comment]
Issue fixed in new plugin code.
